"""Rebuild local-browser assets using Python's standard library only."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parent.parent
VENDOR = ROOT / 'vendor'

def classic_module(source, target):
    text = (VENDOR / source).read_text(encoding='utf-8')
    text = re.sub(r"import\s*\{([\s\S]*?)\}\s*from 'three';", r'const {\1} = window.THREE;', text)
    def exports(match):
        names = []
        for name in match.group(1).split(','):
            parts = name.strip().split(' as ')
            if parts[0]:
                names.append(parts[0] if len(parts) == 1 else parts[1] + ': ' + parts[0])
        return 'Object.assign(window.' + target + ', {' + ', '.join(names) + '});'
    text = re.sub(r'export\s*\{([\s\S]*?)\};', exports, text)
    extra_exports = re.findall(r'export function (\w+)', text)
    text = text.replace('export function ', 'function ')
    if extra_exports:
        text += '\nObject.assign(window.' + target + ', {' + ', '.join(extra_exports) + '});'
    assert not re.search(r'^\s*(import|export)\s', text, re.M), source
    return '(function(){\n"use strict";\n' + text + '\n})();\n'

runtime = '// Three.js r170, original MIT license: LICENSE-three.txt\nwindow.THREE = {};\n'
runtime += classic_module('three.module.js', 'THREE')
(VENDOR / 'three.local.js').write_text(runtime, encoding='utf-8')
addons = 'window.RoachAddons = {};\n'
addons += classic_module('OrbitControls.js', 'RoachAddons')
addons += classic_module('BufferGeometryUtils.js', 'RoachAddons')
(VENDOR / 'addons.local.js').write_text(addons, encoding='utf-8')

pages = {name: (ROOT / name).read_text(encoding='utf-8') for name in ('game.html', 'specimen-lab.html')}
# srcdoc inherits the parent origin, so the existing direct iframe APIs also work
# under file:// without disabling browser security or running a local server.
(ROOT / 'local-pages.js').write_text(
    '// Generated by tools/build-local.py; edit the HTML sources, then rebuild.\n'
    + 'window.ROACH_LOCAL_PAGES = ' + json.dumps(pages, ensure_ascii=False) + ';\n', encoding='utf-8')
print('Built Three.js r170 classic scripts and local page payloads.')
